### ISSUE TITLE
Error: EACCES: permission denied, open '/storage/emulated/0/bunsen/node/index.js'

### ISSUE THREAD

**Issue by chrisekelley** [bunsenbrowser/bunsen#10]
App crashes when starting. This message is in the logs. I think I need to add some permissions to the config.xml file.

**Comment by chrisekelley** [comment]
Log file:

08-02 12:46:04.283 19263 19319 D CordovaNodePlugin: ACTION_START_SERVER: startServer
08-02 12:46:04.283 19263 19263 D CordovaNodePlugin: Starting node. Wheeee!
08-02 12:46:05.375 19263 19321 D Node.js : fs.js:652
08-02 12:46:05.375 19263 19321 D Node.js :   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
08-02 12:46:05.375 19263 19321 D Node.js :                  ^
08-02 12:46:05.375 19263 19321 D Node.js : 
08-02 12:46:05.375 19263 19321 D Node.js : Error: EACCES: per
08-02 12:46:05.375 19263 19321 D Node.js : mission denied, open '/storage/emulated/0/bunsen/node/index.js'
08-02 12:46:05.375 19263 19321 D Node.js :     at Object.fs.openSync (fs.js:652:18)
08-02 12:46:05.375 19263 19321 D Node.js :     at Object.fs.readF
08-02 12:46:05.375 19263 19321 D Node.js : ileSync (fs.js:553:33)
08-02 12:46:05.375 19263 19321 D Node.js :     at Object.Module._extensions..js (module.js:579:20)
08-02 12:46:05.375 19263 19321 D Node.js :     at Module.load (module.js:503:32)
08-02 12:46:05.375 19263 19321 D Node.js :     at try
08-02 12:46:05.375 19263 19321 D Node.js : ModuleLoad (module.js:466:12)
08-02 12:46:05.375 19263 19321 D Node.js :     at Function.Module._load (module.js:458:3)
08-02 12:46:05.375 19263 19321 D Node.js :     at Function.Module.runMain (module.js:605:10)
08-02 12:46:05.375 19263 19321 D Node.js :     at startup (bootstrap_node.js:158:16)
08-02 12:46:05.375 19263 19321 D Node.js :     at bootstrap_node.js:575:3

**Comment by chrisekelley** [comment]
Android 6.0 Marshmallow has a new permissions procedure; for some operations you ust ask permissions. Installed https://github.com/NeoLSN/cordova-plugin-android-permissions and added typings info to typings.d.ts.
