### ISSUE TITLE
RangeError('"port" option should be >= 0 and < 65536: ' + port);

### ISSUE THREAD

**Issue by chrisekelley** [bunsenbrowser/bunsen#13]
Node shared binary needs port.

Error:

```
08-02 13:15:11.634 25767 25891 D Node.js : net.js:1023
08-02 13:15:11.634 25767 25891 D Node.js :       throw new RangeError('"port" option should be >= 0 and < 65536: ' + port);
08-02 13:15:11.634 25767 25891 D Node.js :       ^
08-02 13:15:11.634 25767 25891 D Node.js : 
08-02 13:15:11.634 25767 25891 D Node.js : RangeError: "port" option
08-02 13:15:11.634 25767 25891 D Node.js :  should be >= 0 and < 65536: NaN
08-02 13:15:11.634 25767 25891 D Node.js :     at lookupAndConnect (net.js:1023:13)
08-02 13:15:11.634 25767 25891 D Node.js :     at Socket.connect (net.js:995:5)
08-02 13:15:11.634 25767 25891 D Node.js :     at Object.co
08-02 13:15:11.634 25767 25891 D Node.js : nnect (net.js:108:35)
08-02 13:15:11.634 25767 25891 D Node.js :     at /storage/emulated/0/bunsen/node/index.js:6:20
08-02 13:15:11.634 25767 25891 D Node.js :     at Object.<anonymous> (/storage/emulated/0/bunse
08-02 13:15:11.634 25767 25891 D Node.js : n/node/index.js:12:2)
08-02 13:15:11.634 25767 25891 D Node.js :     at Module._compile (module.js:569:30)
08-02 13:15:11.634 25767 25891 D Node.js :     at Object.Module._extensions..js (module.js:580:10)
08-02 13:15:11.634 25767 25891 D Node.js :     at 
08-02 13:15:11.634 25767 25891 D Node.js : Module.load (module.js:503:32)
08-02 13:15:11.634 25767 25891 D Node.js :     at tryModuleLoad (module.js:466:12)
08-02 13:15:11.634 25767 25891 D Node.js :     at Function.Module._load (module.js:458:3)

```

**Comment by chrisekelley** [comment]
This was resolved by #5677e30ca380e72681d2358233db98c904355fca
The ipc port is hard-coded to 9000.
The node http server runs on port 8080.
