### ISSUE TITLE
npm install fails with "EEXIST: file already exists, mkdir "

### ISSUE THREAD

**Issue by rjsteinert** [bunsenbrowser/bunsen#28]
```
Discovered plugin "cordova-node-plugin" in config.xml. Adding it to the project
shell.js: internal error
Error: EEXIST: file already exists, mkdir '/Users/rjsteinert/Git/bunsenbrowser/bunsen/plugins/cordova-node-plugin'
    at Object.fs.mkdirSync (fs.js:890:18)
    at mkdirSyncRecursive (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mkdir.js:11:8)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mkdir.js:63:7
    at Array.forEach (native)
    at Object._mkdir (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mkdir.js:48:8)
    at Object.mkdir (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/common.js:186:23)
    at copyPlugin (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:367:15)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:223:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
```

**Comment by chrisekelley** [comment]
I have not reproduced this issue now that we've switched to a different lib for the nodejs plugin. Actually, sometimes dealing w/ cordova plugins on Android can be flakey, but lately it has been working fine. Closing.
